// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVQaJYhRmAWPBtWQF9h3iCXvYEdi_NhDs',
    appId: '1:160545783993:web:ecddc9c640a6e7eac0db68',
    messagingSenderId: '160545783993',
    projectId: 'expertsapp-6d278',
    authDomain: 'expertsapp-6d278.firebaseapp.com',
    storageBucket: 'expertsapp-6d278.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmkW7euMAKa3_34_AQUpRLxb2ashCToe4',
    appId: '1:160545783993:ios:37de0d023a38315cc0db68',
    messagingSenderId: '160545783993',
    projectId: 'expertsapp-6d278',
    storageBucket: 'expertsapp-6d278.firebasestorage.app',
    iosBundleId: 'com.example.plantDiagnosisFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVQaJYhRmAWPBtWQF9h3iCXvYEdi_NhDs',
    appId: '1:160545783993:web:baf2ec1c12533f77c0db68',
    messagingSenderId: '160545783993',
    projectId: 'expertsapp-6d278',
    authDomain: 'expertsapp-6d278.firebaseapp.com',
    storageBucket: 'expertsapp-6d278.firebasestorage.app',
  );
}
